version: "3.8"

services:
    app:
        build: .
        image: php:8.2-fpm
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
        expose:
            - "9000"
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        depends_on:
            - app
        networks:
            - laravel_network

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel_db
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - laravel_network

volumes:
    dbdata:

networks:
    laravel_network:
        driver: bridge
